### ISSUE TITLE
ios build error 

### ISSUE THREAD

**Issue by stuart-ithands** [EnableX/One-to-One-Video-Calling-Open-Source-flutter-Application#2]
Hi,
Once I try to create a build for ios I am getting this error:

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_EnxPlayerView

Undefined symbol: _OBJC_CLASS_$_EnxUtilityManager

Undefined symbol: _OBJC_CLASS_$_EnxRtc

**Comment by rohitrvayuz** [comment]
> Hi, Once I try to create a build for ios I am getting this error:
> 
> Showing Recent Messages Undefined symbol: _OBJC_CLASS_$_EnxPlayerView
> 
> Undefined symbol: _OBJC_CLASS_$_EnxUtilityManager
> 
> Undefined symbol: _OBJC_CLASS_$_EnxRtc


1. Select Pods
2. Select enxrtc pod
3. go to build settings
4. change bitcode to NO
5. then change the minimum iOS target on the enxrtc pod to iOS 12.0

@stuart-ithands

**Comment by pankajpandeyvcx** [comment]
resolved
